version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    environment:
      DOCKER_TLS_VERIFY: "1"
      DOCKER_HOST: tcp://40.78.68.74:2376
      DOCKER_CERT_PATH: C:\Users\Terence Machine\.docker\machine\machines\tc-docker
      DOCKER_MACHINE_NAME: tc-docker
      COMPOSE_CONVERT_WINDOWS_PATHS: "true"
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: run service
          command: docker-compose up -d --build

      - run:
          name: unit tests & coding standard check
          command: |
            docker-compose exec users python manage.py test
            docker-compose exec users flake8 project
          
      - run:
          name: stop service
          command: docker-compose down