version: 2
jobs:
  build:
    docker:
      - image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
  test:
    docker:
      - image: circleci/classic:latest
    working_directory: ~/repo
    steps:
      - run:
          name: run service
          command: docker-compose up -d --build

      - run:
          name: unit tests & coding standard
          command: |
            docker-compose exec users python manage.py test
            docker-compose exec users flake8 project
          
      - run:
          name: stop service
          command: docker-compose down